language: node_js
node_js:
 - "node"

script:
- echo “check jsdoc”
- node_modules/.bin/jsdoc src

deploy:
provider : pages
skip-cleanup: true
github-token: $GITHUB_TOKEN
keep-history: true
on: 
branch: master

